/**
 * verify_demo.mjs — Test on-chain proof verification (Phase 4 done-criterion)
 *
 * Runs two cases against the deployed BalanceVerifier contract:
 *   1. POSITIVE: valid Merkle proof for address `1P5ZEDWTKTFGxQjZphgWPQUpe554WKDfHQ`
 *      → transaction succeeds, ProofVerified event emitted
 *   2. NEGATIVE: same proof but with tampered balance
 *      → transaction reverts (Cairo assert fires)
 *
 * Prerequisites:
 *   - deploy.mjs must have run successfully (addresses in .env)
 *   - STARKNET_PRIVATE_KEY + STARKNET_ACCOUNT_ADDRESS set in .env
 *
 * Usage:
 *   node verify_demo.mjs
 *
 * Proof data was computed by the Python backend for the demo snapshot:
 *   address : 1P5ZEDWTKTFGxQjZphgWPQUpe554WKDfHQ
 *   balance : 200,000,000 satoshis  (2 BTC)
 *   height  : 800,000
 *   salt    : 0x1234567890abcdef   (deterministic demo salt)
 */

import { RpcProvider, Account } from 'starknet';
import path from 'path';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..', '..');
dotenv.config({ path: path.join(ROOT, '.env') });

// ─── Demo proof ───────────────────────────────────────────────────────────────
// Calldata layout:
//   [address_hash, salt, balance, path_len,
//    path[0].value, path[0].direction,
//    path[1].value, path[1].direction,
//    path[2].value, path[2].direction,
//    commitment, threshold]
//
// Generated by: backend/src/circuit/proof_generator.py → generate_calldata()
// Verified by:  backend tests (57/57 pass, including proof round-trip tests)

const VALID_CALLDATA = [
  '461883673067612584792338221093381074111200688148327570451060764091247821750', // address_hash
  '1311768467294899695',                                                          // salt
  '200000000',                                                                    // balance (2 BTC)
  '3',                                                                            // merkle_path length
  '1606027379435345129025600649467605874028167328785086011983591641809269492251', // path[0].value
  '1',                                                                            // path[0].direction = Right
  '1273211030432860885457380883246437736983154416911174402242081771522202122897', // path[1].value
  '1',                                                                            // path[1].direction = Right
  '268981268424111534551828952898826710918360351739285386418717985138702640655',  // path[2].value
  '1',                                                                            // path[2].direction = Right
  '3277040955342947357396102218962827964502330469704889508457844397982119416161', // commitment
  '100000000',                                                                    // threshold (1 BTC)
];

// Tampered: wrong balance (999,999,999 instead of 200,000,000)
// The leaf hash will be different → Merkle path won't reach the registered root → revert
const TAMPERED_CALLDATA = [...VALID_CALLDATA];
TAMPERED_CALLDATA[2] = '999999999';

// ─── Helpers ──────────────────────────────────────────────────────────────────

async function waitAndLog(provider, txHash) {
  process.stdout.write(`  TX: ${txHash.slice(0, 18)}… `);
  try {
    const receipt = await provider.waitForTransaction(txHash);
    const status = receipt.execution_status ?? receipt.finality_status ?? 'confirmed';
    return { ok: true, status };
  } catch (e) {
    return { ok: false, error: e.message };
  }
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  const privateKey = process.env.STARKNET_PRIVATE_KEY;
  const accountAddress = process.env.STARKNET_ACCOUNT_ADDRESS;
  const verifierAddress = process.env.BALANCE_VERIFIER_ADDRESS;
  const rpcUrl = process.env.STARKNET_RPC_URL || 'https://starknet-sepolia.public.blastapi.io';

  if (!verifierAddress || verifierAddress === '0x...') {
    console.error('ERROR: BALANCE_VERIFIER_ADDRESS not set. Run deploy.mjs first.');
    process.exit(1);
  }
  if (!privateKey || privateKey === '0x...') {
    console.error('ERROR: STARKNET_PRIVATE_KEY not set in .env');
    process.exit(1);
  }

  console.log('='.repeat(60));
  console.log('Latens — Phase 4: On-Chain Proof Verification Test');
  console.log('='.repeat(60));
  console.log(`Verifier: ${verifierAddress}`);
  console.log(`Account:  ${accountAddress}`);
  console.log('');

  const provider = new RpcProvider({ nodeUrl: rpcUrl });
  const account = new Account(provider, accountAddress, privateKey);

  let passed = 0;

  // ── Test 1: Valid proof ──────────────────────────────────────────────────
  console.log('[1/2] POSITIVE test — valid proof (balance=200000000, threshold=100000000)');
  console.log('  Address: 1P5ZEDWTKTFGxQjZphgWPQUpe554WKDfHQ');
  try {
    const tx = await account.execute([{
      contractAddress: verifierAddress,
      entrypoint: 'verify_proof',
      calldata: VALID_CALLDATA,
    }]);
    const { ok, status, error } = await waitAndLog(provider, tx.transaction_hash);
    if (ok) {
      console.log(`→ ${status}`);
      console.log('  PASS ✓  Transaction succeeded — ProofVerified event emitted\n');
      passed++;
    } else {
      console.log(`→ FAILED`);
      console.error(`  FAIL ✗  ${error}\n`);
    }
  } catch (err) {
    console.error(`  FAIL ✗  ${err?.message ?? err}\n`);
  }

  // ── Test 2: Tampered proof ───────────────────────────────────────────────
  console.log('[2/2] NEGATIVE test — tampered balance (999999999 vs real 200000000)');
  console.log('  Expected: transaction reverts (Merkle root mismatch)');
  try {
    const tx = await account.execute([{
      contractAddress: verifierAddress,
      entrypoint: 'verify_proof',
      calldata: TAMPERED_CALLDATA,
    }]);
    const { ok, status, error } = await waitAndLog(provider, tx.transaction_hash);
    if (!ok) {
      console.log(`→ reverted`);
      console.log('  PASS ✓  Transaction reverted as expected\n');
      passed++;
    } else {
      // Some verifiers return false instead of reverting — check receipt events
      console.log(`→ ${status} (unexpected success)`);
      console.error('  FAIL ✗  Transaction succeeded but should have reverted\n');
    }
  } catch (err) {
    const msg = err?.message ?? '';
    if (
      msg.includes('revert') ||
      msg.includes('Proof') ||
      msg.includes('REVERTED') ||
      msg.includes('Error in the called contract')
    ) {
      console.log('→ reverted');
      console.log('  PASS ✓  Transaction reverted as expected\n');
      passed++;
    } else {
      console.error(`  FAIL ✗  Unexpected error: ${msg}\n`);
    }
  }

  // ── Summary ───────────────────────────────────────────────────────────────
  console.log('='.repeat(60));
  if (passed === 2) {
    console.log(`Phase 4 COMPLETE ✓  (${passed}/2 tests passed)`);
    console.log('Both positive and negative cases pass on Sepolia.');
  } else {
    console.log(`${passed}/2 tests passed — check errors above.`);
  }
  console.log('='.repeat(60));

  process.exit(passed === 2 ? 0 : 1);
}

main().catch(err => {
  console.error('Verification failed:', err?.message ?? err);
  process.exit(1);
});
